name: Waka Readme

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: no
          SHOW_PROJECTS: no
          SHOW_PROFILE_VIEWS: no
          SHOW_LANGUAGE_PER_REPO: no
          SHOW_LOC_CHART: no
          SHOW_UPDATED_DATE: no
          SHOW_TOTAL_CODE_TIME: no
